// <auto-generated />
namespace HospitalDataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-beta1-40122")]
    public sealed partial class Lastone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Lastone));
        
        string IMigrationMetadata.Id
        {
            get { return "201607140958006_Lastone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
